[package]
name = "irondict-gui"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
irondict-core = { path = "../core" }
regex = "1.12.3"
rfd = { version = "0.15", default-features = false, features = ["xdg-portal", "async-std"] }
slint = "1"
zbus = "5.16.0"

[build-dependencies]
slint-build = "1"
