[package]
name = "irondict-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
stardict = { version = "0.2", default-features = false }
thiserror = "2"
serde = { version = "1", features = ["derive"] }
toml = "0.8"
directories = "5"
tantivy = "0.26.1"
unicode-normalization = "0.1"
ureq = "2"
ruzstd = "0.8.3"
tar = "0.4.46"
rayon = "1"
